services:
  backend:
    container_name: hr_ai_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - hrai-network

  frontend:
    container_name: hr_ai_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    ports:
      - "3000:3000"
    networks:
      - hrai-network

networks:
  hrai-network:
    driver: bridge
